### ISSUE TITLE
Support for reordering tables and perhaps lists

### ISSUE THREAD

**Issue by jnnkB** [GetmeUK/contenttools-2-roadmap#13]
I think it would be really useful if you could tables would be sortable. Perhaps one could introduce a handle for this. 

I guess it's also interesting for lists, but this seems to be easier to archive with copy and paste than reordering tables.

**Comment by anthonyjb** [comment]
@jnnkB this is already supported list items and table rows. Click and hold on an element for .5 seconds until the item or row becomes faded and the helper appears then move the mouse over the element to move the item/row to. You can also click and hold longer for the option to move the entire list or table.

**Comment by jnnkB** [comment]
Thanks a lot. This is really cool.
