### ISSUE TITLE
Add php Saving method

### ISSUE THREAD

**Issue by ElStefanos** [GetmeUK/contenttools-2-roadmap#9]
I'm developing an open source CMS and i want to implement content tools however big minus is that i can't implement php saving method. However other WYIWYG tools require additional packages like nodeJS that needs to be manually installed on server also they are not as good as ContentTools. I actually need php saving method because most of webhosting companies have php pre-installed.

**Comment by kriskenyon** [comment]
@ElStefanos I have been using content tools for years and always use php to save. Content tools is a Javascript library an as such runs in the users browser.  From there you would send your edits to ANY backend including PHP to save.  You may want to look at implementing a REST Api for your PHP code to make it easier to manage the sending and receiving of data from all your javascript functions.

**Comment by ElStefanos** [comment]
@kriskenyon i thought of that but because of the docs on content tools i thought it can't be done. Thanks.

**Comment by anthonyjb** [comment]
Hi @ElStefanos, as @kriskenyon ContentTools is a frontend JavaScript library and makes no assumptions about the backend.

I'm not a proficient PHP user I'm afraid and so my saving tutorial uses Python, however, if someone wants to convert the tutorial code snippets to PHP (or other languages) I'd gladly either link to or find a way to host the additional code to help users coming to CT from other languages.
